// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Quiz.DataBase;

namespace Quiz.Migrations
{
    [DbContext(typeof(PostgresContext))]
    partial class PostgresContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("Quiz.DataBase.Counter", b =>
                {
                    b.Property<int>("IdNote")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.HasKey("IdNote");

                    b.ToTable("Counters");

                    b.HasData(
                        new
                        {
                            IdNote = 273314807,
                            Id = 1,
                            Value = 1
                        },
                        new
                        {
                            IdNote = -578715950,
                            Id = 1,
                            Value = 2
                        },
                        new
                        {
                            IdNote = 1203322088,
                            Id = 1,
                            Value = 3
                        },
                        new
                        {
                            IdNote = 599104171,
                            Id = 2,
                            Value = 1
                        },
                        new
                        {
                            IdNote = -665040943,
                            Id = 2,
                            Value = 1
                        },
                        new
                        {
                            IdNote = 1747910321,
                            Id = 2,
                            Value = 3
                        },
                        new
                        {
                            IdNote = -1267453471,
                            Id = 2,
                            Value = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
